export async function GET() {
  const troySaga = {
    saga: "troy",
    sagaTitle: "The Troy Saga",
    themeGradient: "from-sky-950 via-red-500 to-sky-950",
    songs: [
      {
        id: 1,
        title: "The Horse and the Infant",
        saga: "The Troy Saga",
        characters: ["Odysseus", "Zeus", "Odysseus' Crew"],
        video: "https://www.youtube.com/embed/OE8TQBqWVV8?si=1QzVuqFEQrIL3pZ8",
        lyrics: [
          "[ODYSSEUS]",
          "Alright, my brothers, listen closely",
          "Tonight we make the Trojans pay",
          "Ten years of war, they killed us slowly",
          "But now we'll be the ones who slay",
          "Think of your wives and your children",
          "Your families wonder where you've been",
          "They're growin' old, and yet you're still here",
          "Do what I say and you'll see them again",
          "[ODYSSEUS' CREW]",
          "Yes, sir",
          "[ODYSSEUS]",
          "Diomedes will lead the charge",
          "Agamemnon will flank the guards",
          "Menelaus will let our mates through the gates",
          "To take the whole city at large",
          "Teucer will shoot any ambush attack",
          "And Little Ajax will stay back",
          "Nestor, secure Helen and protect her",
          "Neo, avenge your father, kill the brothers of Hector",
          "[SOLDIERS]",
          "Yes, Sir",
          "[ODYSSEUS, SOLDIERS]",
          "Find that inner strength now (Huh)",
          "Use that well of pride (Huh)",
          "Fight through every pain now (Huh)",
          "Ask yourself inside",
          "What do you live for? What do you try for?",
          "What do you wish for? What do you fight for?",
          "[SOLDIERS]",
          "What do you live for? What do you try for?",
          "What do you wish for? What do you fight for?",
          "[ODYSSEUS]",
          "Penelope, Penelope",
          "And Telemachus",
          "I fight for us, I fight for us",
          "[SOLDIERS]",
          "What do you live for?",
          "[ODYSSEUS, spoken]",
          "Penelope",
          "[SOLDIERS]",
          "What do you try for?",
          "[ODYSSEUS, spoken]",
          "Telemachus",
          "[SOLDIERS]",
          "What do you wish for?",
          "[ODYSSEUS, spoken]",
          "I'm on my way",
          "[SOLDIERS]",
          "What do you fight for?",
          "[ODYSSEUS, spoken]",
          "Attack!",
          "[Battle cries and war sounds are heard A figure approaches ODYSSEUS and stabs him]",
          "[ODYSSEUS, spoken]",
          "Argh",
          "Who was that?",
          "[Thunder, an eagle cries]",
          "[ZEUS]",
          "A vision of what is to come, cannot be outrun",
          "Can only be dealt with right here and now",
          "[ODYSSEUS]",
          "Tell me how",
          "[ZEUS]",
          "I don't think you're ready",
          "A mission to kill someone's son, a foe who won't run",
          "Unlike anyone you have faced before",
          "[ODYSSEUS]",
          "Say no more, I know that I'm ready",
          "[ZEUS & GODS]",
          "I don't think you're ready",
          "[ODYSSEUS]",
          "It's just an infant, it's just a boy",
          "What sort of imminent threat does he pose",
          "That I cannot avoid?",
          "[ZEUS]",
          "This is the son of none other",
          "Than Troy's very own Prince Hector",
          "Know that he will grow from a boy to an avenger",
          "One fumed with rage as you're consumed by age",
          "[ZEUS & GODS]",
          "If you don't end him now, you'll have no one left to save",
          "[ZEUS]",
          "You can say goodbye to",
          "[GODS]",
          "Penelope",
          "[ZEUS]",
          "You can say goodbye to",
          "[GODS]",
          "Penelope",
          "[ODYSSEUS, ZEUS & GODS]",
          "I could raise him as my own",
          "He will burn your house and throne",
          "Or send him far away from home",
          "He'll find you wherever you go",
          "Make sure his past is never known",
          "The gods will make him known",
          "I'd rather bleed for ya, I'm on my knees for ya",
          "They're bringing you down on your knees for ya",
          "I'm beggin' please",
          "Oh, this is the will of the gods",
          "[ODYSSEUS]",
          "Please don't make me do this, don't make me do this",
          "[ZEUS]",
          "The blood on your hands is something you won't lose",
          "[ZEUS & GODS]",
          "All you can choose is whose",
        ],
      },
      {
        id: 2,
        title: "Just A Man",
        saga: "The Troy Saga",
        characters: ["Odysseus", "Odysseus' Crew"],
        video: "https://www.youtube.com/embed/XcaJTJ_viN8?si=k8kwnvbUSxM5yfq9",
        lyrics: [
          "[ODYSSEUS]",
          "I look into your eyes and I",
          "Think back to the son of mine",
          "You're as old as he was when I left for war",
          "Will these actions haunt my days? Every man I’ve slain?",
          "Is the price I pay endless pain?",
          "Close your eyes and spare yourself the view",
          "How could I hurt you?",
          "I'm just a man who's trying to go home",
          "Even after all the years away from what I’ve known",
          "I'm just a man who's fighting for his life",
          "Deep down I would trade the world to see my son and wife",
          "I'm just a man",
          "But when does a comet become a meteor?",
          "When does a candle become a blaze?",
          "When does a man become a monster?",
          "When does a ripple become a tidal wave?",
          "When does the reason become the blame?",
          "When does a man become a monster?",
          "[ODYSSEUS, ODYSSEUS' CREW]",
          "When does a comet become a meteor?",
          "When does a candle become a blaze? (Forgive me)",
          "When does a man become a monster? (Forgive me)",
          "When does a man become a monster? (Forgive me)",
          "I'm just a man",
        ],
      },
      {
        id: 3,
        title: "Full Speed Ahead",
        saga: "The Troy Saga",
        characters: ["Odysseus", "Eurylochus", "Polites", "Odysseus' Crew"],
        video: "https://www.youtube.com/embed/x3KOt-3T73c?si=zFJjk3_F9m_QLdy8",
        lyrics: [
          "[ODYSSEUS, ODYSSEUS' CREW]",
          "Six hundred men",
          "Six hundred men under my command",
          "With only one goal in mind:",
          "Make it back alive to our homeland",
          "Six hundred men, six hundred miles of open sea",
          "But the problem's not the distance",
          "It's what lies in between",
          "And Ithaca's waiting (Ithaca's waiting)",
          "My kingdom is waiting (The kingdom is waiting)",
          "Penelope's waitin' for me",
          "So full speed ahead, full speed ahead",
          "[EURYLOCHUS, ODYSSEUS' CREW]",
          "Captain (Eurylochus)",
          "Six hundred men (Six hundred men)",
          "Six hundred men with big mouths to feed",
          "And we've run out of supplies to eat",
          "Curse the war, our food store's depleted",
          "Six hundred men (Six hundred men)",
          "Six hundred reasons to take what we can",
          "So Captain, what's the plan?",
          "Captain, what's the plan?",
          "[ODYSSEUS, ODYSSEUS' CREW]",
          "Watch where the birds fly (Watch where the birds fly)",
          "They will lead us to land (They will lead us to land)",
          "There we'll hunt for food, my second in command",
          "Now full speed ahead",
          "[EURYLOCHUS]",
          "We're up, we're off, and away we go",
          "[EURYLOCHUS & ODYSSEUS' CREW]",
          "We're up, we're off, and away we go",
          "[ODYSSEUS]",
          "Full speed ahead",
          "[ODYSSEUS' CREW]",
          "We're up, we're off, and away we go",
          "[POLITES]",
          "Captain",
          "[ODYSSEUS]",
          "Polites",
          "[POLITES]",
          "Look! There in the distance, I see an island",
          "I see a light that faintly glows",
          "Maybe they're people lighting a fire",
          "Maybe they'll share some food, who knows?",
          "[ODYSSEUS]",
          "Something feels off here, I see fire but there's no smoke",
          "[EURYLOCHUS]",
          "I say we strike first, we don't have time to waste",
          "So let's raid the place and—",
          "[ODYSSEUS, spoken]",
          "No",
          "[ODYSSEUS]",
          "Polites, gear up, you and I'll go ahead",
          "[POLITES]",
          "You and I'll go ahead",
          "[ODYSSEUS]",
          "We should try to find a way no one ends up dead",
          "[EURYLOCHUS]",
          "We don't know what's ahead",
          "[ODYSSEUS, ODYSSEUS' CREW]",
          "Give me 'til sunrise, and if we don't return",
          "Then six hundred men can make this whole place burn",
          "Now full speed ahead, full speed ahead",
          "Full speed ahead",
          "We're up, we're off, and away we go",
          "We're up, we're off, and away we go",
          "Full speed ahead",
          "We're up, we're off, and away we go",
          "We're up, we're off, and a—",
          "Full speed ahead",
        ],
      },
      {
        id: 4,
        title: "Open Arms",
        saga: "The Troy Saga",
        characters: ["Odysseus", "Polites", "Lotus Eaters"],
        video: "https://www.youtube.com/embed/-oMZw8DQbaI?si=5tGK5-4A30rEqu0Z",
        lyrics: [
          "[POLITES]",
          "You can relax, my friend",
          "[ODYSSEUS, spoken]",
          "Huh?",
          "[POLITES]",
          "I can tell you're getting nervous",
          "So do yourself a service",
          "And try to relax, my friend",
          "[ODYSSEUS]",
          "I'm fine, Polites",
          "[POLITES]",
          "Think of all that we have been through",
          "We'll survive what we get into",
          "I know that you're tired of the war and bloodshed",
          "Tell me, is this how we're supposed to live?",
          "Look at how you grip your sword, enough said",
          "Why should we take when we could give?",
          "You can show a person that you trust them",
          "When you stop and lower your guard",
          "Here we have a chance for some adjustment",
          "Give it a try, it's not that hard",
          "I'm telling you",
          "This life is amazing when you greet it with open arms",
          "Whatever we face, we'll be fine if we're leading from the heart",
          "No matter the place, we can light up the world",
          "Here's how to start",
          "Greet the world with open arms",
          "Greet the world with open arms",
          "[LOTUS EATERS, spoken]",
          "Welcome",

          "[ODYSSEUS, spoken]",
          "Stay back",
          "[LOTUS EATERS, spoken]",
          "Stay back",
          "[POLITES]",
          "My friend, greet the world with open arms",
          "[ODYSSEUS]",
          "We're only here for food",
          "[LOTUS EATERS, spoken]",
          "Food",
          "[ODYSSEUS]",
          "Six hundred friends are waiting for us to show our faces",
          "[LOTUS EATERS, spoken]",
          "Food",
          "[ODYSSEUS]",
          "Stay back, I'm warning you",
          "[LOTUS EATERS, spoken]",
          "Food (Num num num)",
          "[ODYSSEUS]",
          "If we don't get back safely",
          "My men will turn this place into blazes",
          "[LOTUS EATERS, spoken]",
          "Here you go",
          "[POLITES]",
          "See? This life is amazing when you greet it with open arms",
          "Whatever we face, we'll be fine if we're leading from the heart",
          "No matter the place, we can light up the world",
          "Here's how to start",
          "Greet the world with open arms",
          "Greet the world with open arms",
          "[ODYSSEUS]",
          "My friend, I wish that I could say that I agree",
          "But look at the way this fruit is glowing",
          "And filled with glowing seeds",
          "It took me a while to notice just what kind of fruit they eat",
          "It's a lotus, it controls your mind and never lets you free",
          "That's what we'd get with open arms",
          "[POLITES]",
          "Lotus eaters, I'd like to show my friend that kindness is brave",
          "Could you tell me where there's other food to eat?",
          "[LOTUS EATERS, spoken]",
          "The cave (Scary cave)",
          "[POLITES]",
          "A cave! You're saying there's a cave where we could feast?",
          "And where do we sail to find this food-filled cave?",
          "[LOTUS EATERS, spoken]",
          "East (That way)",
          "[POLITES, spoken]",
          "Thank you",
          "[LOTUS EATERS, spoken]",
          "Welcome",
          "[POLITES]",
          "This life is amazing when you greet it with open arms",
          "I see in your face, there is so much guilt inside your heart",
          "So why not replace it and light up the world?",
          "Here's how to start",
          "Greet the world with open arms",
          "Greet the world with open arms",
          "[ODYSSEUS]",
          "Greet the world with open arms",
          "[POLITES]",
          "You can relax, my friend",
        ],
      },
      {
        id: 5,
        title: "Warrior of the Mind",
        saga: "The Troy Saga",
        characters: ["Odysseus", "Athena"],
        video: "https://www.youtube.com/embed/oB8lqgO9e24?si=CdmiotmfbelfbGAE",
        lyrics: [],
      },
    ],
  };

  return new Response(JSON.stringify(troySaga), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*", // Allow requests from any origin
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
